spring:
  application:
    name: graphql-todo-app
  servlet:
    multipart:
      enabled: true
      location: /tmp
  datasource:
    initialize: true
    initialization-mode: always
    url: jdbc:h2:mem:test
#    url: jdbc:h2:/tmp/test;DB_CLOSE_ON_EXIT=TRUE;IFEXISTS=FALSE
  h2:
    console:
      enabled: true
server:
  port: 9000
