spring:
  application:
    name: graphql-todo-app
  servlet:
    multipart:
      enabled: true
      location: /tmp
  datasource:
    initialize: true
    initialization-mode: always
    testOnBorrow: true
    validationQuery: SELECT 1

#    url: jdbc:h2:mem:test
    url: jdbc:h2:/tmp/test;DB_CLOSE_ON_EXIT=TRUE;IFEXISTS=FALSE
#    url: jdbc:h2:tcp://localhost/mem:test
  h2:
    console:
      enabled: true
server:
  port: 9000
